x-common-config:
  &common-config
  network_mode: host
  ipc: host
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  env_file: .env.dds

x-gui-config:
  &gui-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-1}
    - NVIDIA_VISIBLE_DEVICES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored
    - NVIDIA_DRIVER_CAPABILITIES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored

services:
  teleop:
    build:
      context: .
      dockerfile: Dockerfile.teleop
    <<:
      - *common-config
      - *gui-config
    command: >
      ros2 run rqt_image_view rqt_image_view /oak/rgb/image_raw/compressed
  joy2twist:
    image: husarion/joy2twist:humble-1.0.0-20240105
    <<:
      - *common-config
    devices:
      - /dev/input
    volumes:
      - ./config/joy2twist.yaml:/params.yaml
    command: >
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/params.yaml
