x-common-config:
  &common-config
  network_mode: host
  ipc: host 
  pid: host # ?
  restart: unless-stopped
  env_file: .env.dds

services:
  rosbot:
    image: husarion/rosbot-xl:humble-0.10.0-20240216
    <<:
      - *common-config
    command: >
      ros2 launch /husarion_utils/rosbot.launch.py
        mecanum:=${MECANUM:-True}
        include_camera_mount:=True
        healthcheck:=True

  luxonis:
    image: husarion/depthai:humble-2.8.1-20240127
    <<:
      - *common-config
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./config/oak-1.yaml:/params.yaml
    device_cgroup_rules:
      - 'c 189:* rmw'
    depends_on:
      rosbot: { condition: service_healthy }
    command: >
      ros2 launch depthai_ros_driver camera.launch.py
        params_file:=/params.yaml
        parent_frame:=camera_mount_link

  docking:
    build:
      context: .
      dockerfile: Dockerfile.docking
    <<:
      *common-config
    depends_on:
      rosbot: { condition: service_healthy }
    volumes:
      - ./config/aruco_tracker.yaml:/aruco_tracker.yaml
      - ./config/nav2_docking_server.navless.yaml:/nav2_docking_server.yaml
    command: >
      ros2 launch rosbot_xl_docking docking.launch.py
        aruco_tracker_params_file:=/aruco_tracker.yaml
        nav2_docking_server_params_file:=/nav2_docking_server.yaml
