ARG ROS_DISTRO=humble
FROM husarnet/ros:${ROS_DISTRO}-ros-core

WORKDIR /ros2_ws

# In version 1.0.12 MPPI doesn't work on RPi4 (build from source)
# Install everything needed
RUN apt-get update --fix-missing && \
    apt upgrade -y && \
    apt-get install -y \
        ros-dev-tools

# Install dependencies
COPY rosbot_xl_docking/package.xml src/rosbot_xl_docking/package.xml
RUN rm -rf /etc/ros/rosdep/sources.list.d/20-default.list && \
    rosdep init && \
    rosdep update --rosdistro $ROS_DISTRO && \
    rosdep install -i --from-path src --rosdistro $ROS_DISTRO -y

# Build
COPY rosbot_xl_docking src/rosbot_xl_docking
RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release && \
    rm -rf build log

CMD ["ros2", "launch", "rosbot_xl_docking", "docking.launch.py"]
